In [2]:
#Import Libraries
import pandas as pd
import numpy as np

In [3]:
### Create a list of Column Names (the monthly dates) we can slap on each import
column_name_list = pd.read_excel("SP500_Index_Data_values_only.xlsx", sheet_name="Ticker", 
                   header=0, usecols="R:JD", skiprows=2, nrows=1, 
                   na_values=None, na_filter=False, parse_dates=True).columns.to_list()

print(column_name_list[:5])
print(column_name_list[-5:])

[Timestamp('2021-06-30 00:00:00'), Timestamp('2021-05-31 00:00:00'), Timestamp('2021-04-30 00:00:00'), Timestamp('2021-03-31 00:00:00'), Timestamp('2021-02-28 00:00:00')]
[Timestamp('2001-04-30 00:00:00'), Timestamp('2001-03-31 00:00:00'), Timestamp('2001-02-28 00:00:00'), Timestamp('2001-01-31 00:00:00'), Timestamp('2000-12-31 00:00:00')]

In [4]:
### Create a ticker_df that will be the starting point of our loop to merge the other sheets of the excel file
ticker_df = pd.read_excel("SP500_Index_Data_values_only.xlsx", sheet_name="Ticker", 
                   names=column_name_list, header=0, usecols="R:JD", skiprows=10, nrows=505, 
                   na_values=None, keep_default_na=False, na_filter=False, parse_dates=True)

ticker_df

,2021-06-30,2021-05-31,2021-04-30,2021-03-31,2021-02-28,2021-01-31,2020-12-31,2020-11-30,2020-10-31,2020-09-30,...,2001-09-30,2001-08-31,2001-07-31,2001-06-30,2001-05-31,2001-04-30,2001-03-31,2001-02-28,2001-01-31,2000-12-31
0,LYB UN Equity,LYB UN Equity,LYB UN Equity,LYB UN Equity,PSX UN Equity,PSX UN Equity,PSX UN Equity,WEC UN Equity,WEC UN Equity,WEC UN Equity,...,EIX UN Equity,EIX UN Equity,EIX UN Equity,EIX UN Equity,BF/B UN Equity,BF/B UN Equity,BF/B UN Equity,BF/B UN Equity,BF/B UN Equity,BF/B UN Equity
1,AXP UN Equity,AXP UN Equity,AXP UN Equity,AXP UN Equity,HD UN Equity,HD UN Equity,HD UN Equity,NWS UW Equity,NWS UW Equity,NWS UW Equity,...,AA UN Equity,AA UN Equity,AA UN Equity,AA UN Equity,CSC UN Equity,CSC UN Equity,CSC UN Equity,KRB UN Equity,KRB UN Equity,KRB UN Equity
2,VZ UN Equity,VZ UN Equity,VZ UN Equity,VZ UN Equity,WMT UN Equity,WMT UN Equity,WMT UN Equity,APTV UN Equity,APTV UN Equity,APTV UN Equity,...,AXP UN Equity,VZ UN Equity,VZ UN Equity,VZ UN Equity,3692470Q UN Equity,3692470Q UN Equity,3692470Q UN Equity,AEE UN Equity,AEE UN Equity,AEE UN Equity
3,AVGO UW Equity,AVGO UW Equity,AVGO UW Equity,AVGO UW Equity,DG UN Equity,DG UN Equity,DG UN Equity,XOM UN Equity,XOM UN Equity,XOM UN Equity,...,VZ UN Equity,NRTLQ UN Equity,NRTLQ UN Equity,NRTLQ UN Equity,ANDW UQ Equity,ANDW UQ Equity,ANDW UQ Equity,ITT UN Equity,ITT UN Equity,ITT UN Equity
4,BA UN Equity,BA UN Equity,BA UN Equity,BA UN Equity,KMI UN Equity,KMI UN Equity,KMI UN Equity,HPQ UN Equity,HPQ UN Equity,HPQ UN Equity,...,NRTLQ UN Equity,CAT UN Equity,CAT UN Equity,CAT UN Equity,KRB UN Equity,KRB UN Equity,KRB UN Equity,AA UN Equity,AA UN Equity,AA UN Equity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,ZTS UN Equity,HON UN Equity,HON UN Equity,HON UN Equity,FTI UN Equity,FTI UN Equity,FTI UN Equity,ZTS UN Equity,ZTS UN Equity,ZTS UN Equity,...,,,,,,,,,,
501,EQIX UW Equity,SHW UN Equity,SHW UN Equity,SHW UN Equity,WYNN UW Equity,WYNN UW Equity,WYNN UW Equity,DLR UN Equity,DLR UN Equity,DLR UN Equity,...,,,,,,,,,,
502,DLR UN Equity,VAR UN Equity,VAR UN Equity,VAR UN Equity,ALB UN Equity,ALB UN Equity,ALB UN Equity,EQIX UW Equity,EQIX UW Equity,EQIX UW Equity,...,,,,,,,,,,
503,LVS UN Equity,FISV UW Equity,FISV UW Equity,FISV UW Equity,9990302D UW Equity,9990302D UW Equity,9990302D UW Equity,LVS UN Equity,LVS UN Equity,LVS UN Equity,...,,,,,,,,,,
504,DISCK UW Equity,AMT UN Equity,AMT UN Equity,AMT UN Equity,VNT UN Equity,VNT UN Equity,VNT UN Equity,DISCK UW Equity,DISCK UW Equity,DISCK UW Equity,...,,,,,,,,,,

In [5]:
### Put our starting point in "long format" with melt
### Loop through the data items we want in the excel workbook and concat them

excel_data_df = ticker_df.melt( var_name='Date', value_name='Ticker')

excel_sheet_list = [
                    'Name',
                    'Sector',
                    'Price',
                    'Local_Returns_12m',
                    'Local_Returns_1m',
    
                    'Trail_DivYld',
                    'PB',
                    'Trail_EV_EBITDA',
                    'Trail_PE',
                    'Trail_EPS',
                    'Trail3yrAvg_EPSgro',
                    'Trail3yrAvg_DPSgro',
                    'Volatility',
                    'Debt_to_MktCap',
                    'NetDebt_EBITDA',
                                       ]

for sheet in excel_sheet_list:
    print(sheet)
    temp_df = pd.read_excel("SP500_Index_Data_values_only.xlsx", sheet_name=sheet, 
                   names=column_name_list, header=0, usecols="R:JD", skiprows=10, nrows=505, 
                   na_values=None, keep_default_na=False, na_filter=False, parse_dates=True)
    
    temp_df = temp_df.melt( var_name='Date', value_name=sheet).drop(['Date'], axis=1)
    
    excel_data_df = pd.concat([excel_data_df, temp_df], axis=1)
    
del temp_df

Name
Sector
Price
Local_Returns_12m
Local_Returns_1m
Trail_DivYld
PB
Trail_EV_EBITDA
Trail_PE
Trail_EPS
Trail3yrAvg_EPSgro
Trail3yrAvg_DPSgro
Volatility
Debt_to_MktCap
NetDebt_EBITDA

In [6]:
### .info() for sanity check
excel_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124735 entries, 0 to 124734
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                124735 non-null  datetime64[ns]
 1   Ticker              124735 non-null  object
 2   Name                123868 non-null  object
 3   Sector              124735 non-null  object
 4   Price               124735 non-null  object
 5   Local_Returns_12m   124735 non-null  object
 6   Local_Returns_1m    124735 non-null  object
 7   Trail_DivYld        124735 non-null  object
 8   PB                  124735 non-null  object
 9   Trail_EV_EBITDA     124735 non-null  object
 10  Trail_PE            124735 non-null  object
 11  Trail_EPS           124735 non-null  object
 12  Trail3yrAvg_EPSgro  124735 non-null  object
 13  Trail3yrAvg_DPSgro  124735 non-null  object
 14  Volatility          124735 non-null  object
 15  Debt_to_MktCap      124735 non-null  object
 16  NetDebt_EBITDA      124735 non-null  object
dtypes: datetime64[ns](1), object(16)
memory usage: 16.2+ MB

In [7]:
### Peek at the dataframe for sanity check
excel_data_df

,Date,Ticker,Name,Sector,Price,Local_Returns_12m,Local_Returns_1m,Trail_DivYld,PB,Trail_EV_EBITDA,Trail_PE,Trail_EPS,Trail3yrAvg_EPSgro,Trail3yrAvg_DPSgro,Volatility,Debt_to_MktCap,NetDebt_EBITDA
0,2021-06-30,LYB UN Equity,LYONDELLBASELL-A,Materials,102.87,0.639834,-0.0776916,4.1606,3.908,13.3578,13.4336,7.6577,16.9882,4.0447,40.193,0.4833,3.9745
1,2021-06-30,AXP UN Equity,AMERICAN EXPRESS,Financials,165.23,0.762142,0.0318491,1.041,5.4268,11.45,27.1314,8.6,165.585,7.8788,34.862,0.3285,0.3249
2,2021-06-30,VZ UN Equity,VERIZON COMMUNIC,Communication Services,56.03,0.0613854,-0.00814303,4.4574,3.1481,8.6097,10.4378,5.368,10.8359,2.0861,15.239,0.7723,3.6833
3,2021-06-30,AVGO UW Equity,BROADCOM INC,Information Technology,476.84,0.56111,0.0173708,2.9465,9.665,17.2061,40.4239,11.796,23.7943,30.8588,30.25,0.2067,2.3997
4,2021-06-30,BA UN Equity,BOEING CO/THE,Industrials,239.56,0.306928,-0.0302,0,#N/A N/A,#N/A N/A,#N/A N/A,-8.112,-51.6859,0,46.282,0.4538,#N/A N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124730,2000-12-31,,NaN,x,x,x,x,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security,#N/A Mandatory parameter [SECURITY] cannot be ...,#N/A Invalid Security,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security
124731,2000-12-31,,NaN,x,x,x,x,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security,#N/A Mandatory parameter [SECURITY] cannot be ...,#N/A Invalid Security,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security
124732,2000-12-31,,NaN,x,x,x,x,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security,#N/A Mandatory parameter [SECURITY] cannot be ...,#N/A Invalid Security,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security
124733,2000-12-31,,NaN,x,x,x,x,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security,#N/A Mandatory parameter [SECURITY] cannot be ...,#N/A Invalid Security,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security
124734,2000-12-31,,NaN,x,x,x,x,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security,#N/A Mandatory parameter [SECURITY] cannot be ...,#N/A Invalid Security,x,#N/A Invalid Security,#N/A Invalid Security,#N/A Invalid Security

Basic Data Cleaning

In [8]:
### We know there are several "junk" values in the excel workbook that we need to remove...
### replace those values with np.nan
### remove any 'Ticker' that doesn't exist (had "Junk" in the cell)

df = excel_data_df.copy()
df.replace(to_replace=['x', '#N/A N/A', 
                       '#N/A Invalid Security', '', 
                       '#N/A Mandatory parameter [SECURITY] cannot be empty', 
                       'na',
                       '#N/A Requesting Data...',
                       ],
           value=np.nan, inplace=True, limit=None, regex=False, method='pad')

df = df[~df['Ticker'].isna()]

#df

In [9]:
### We know for certain columns we want to 'force' a float data type
for column in df.columns[4:]:
    df[column] = df[column].astype(float)

In [10]:
### Sanity check for the columns we wante to be float data type
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123868 entries, 0 to 124729
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                123868 non-null  datetime64[ns]
 1   Ticker              123868 non-null  object
 2   Name                123645 non-null  object
 3   Sector              123868 non-null  object
 4   Price               119125 non-null  float64
 5   Local_Returns_12m   122563 non-null  float64
 6   Local_Returns_1m    123681 non-null  float64
 7   Trail_DivYld        123681 non-null  float64
 8   PB                  119890 non-null  float64
 9   Trail_EV_EBITDA     106195 non-null  float64
 10  Trail_PE            116624 non-null  float64
 11  Trail_EPS           116786 non-null  float64
 12  Trail3yrAvg_EPSgro  106237 non-null  float64
 13  Trail3yrAvg_DPSgro  123681 non-null  float64
 14  Volatility          122730 non-null  float64
 15  Debt_to_MktCap      122816 non-null  float64
 16  NetDebt_EBITDA      106751 non-null  float64
dtypes: datetime64[ns](1), float64(13), object(3)
memory usage: 17.0+ MB

In [11]:
### Our Ticker column has some extraneous or unnecessary values we can get rid of:
### We use a regex to do so:
df['Ticker'] = df.Ticker.str.replace(' U. Equity', '', n=- 1, case=None, flags=0, regex=True)
#df

In [12]:
### sanity check of our ticker cleaning
df.Ticker.unique()

array(['LYB', 'AXP', 'VZ', 'AVGO', 'BA', 'CAT', 'JPM', 'CVX', 'KO',
       'ABBV', 'DIS', 'FLT', 'EXR', 'XOM', 'PSX', 'GE', 'HPQ', 'HD',
       'MPWR', 'IBM', 'JNJ', 'MCD', 'MRK', 'MMM', 'AWK', 'BAC', 'BKR',
       'PFE', 'PG', 'T', 'TRV', 'RTX', 'ADI', 'WMT', 'CSCO', 'INTC', 'GM',
       'MSFT', 'DG', 'CI', 'KMI', 'C', 'AIG', 'MO', 'HCA', 'UAA', 'IP',
       'HPE', 'ABT', 'AFL', 'APD', 'RCL', 'HES', 'ADM', 'ADP', 'VRSK',
       'AZO', 'AVY', 'ENPH', 'MSCI', 'BLL', 'CARR', 'BK', 'OTIS', 'BAX',
       'BDX', 'BRK/B', 'BBY', 'BSX', 'BMY', 'FBHS', 'BF/B', 'COG', 'CPB',
       'KSU', 'HLT', 'CCL', 'QRVO', 'LUMN', 'UDR', 'CLX', 'PAYC', 'CMS',
       'NWL', 'CL', 'CMA', 'IPGP', 'CAG', 'ED', 'GLW', 'CMI', 'CZR',
       'DHR', 'TGT', 'DE', 'D', 'DOV', 'LNT', 'DUK', 'REG', 'ETN', 'ECL',
       'PKI', 'EMR', 'EOG', 'AON', 'ETR', 'EFX', 'IQV', 'IT', 'FDX',
       'FMC', 'F', 'NEE', 'BEN', 'FCX', 'GPS', 'DXCM', 'GD', 'GIS', 'GPC',
       'ATO', 'GWW', 'HAL', 'LHX', 'PEAK', 'CTLT', 'FTV', 'HSY', 'SYF',
       'HRL', 'AJG', 'MDLZ', 'CNP', 'HUM', 'WLTW', 'ITW', 'CDW', 'TT',
       'IPG', 'IFF', 'J', 'GNRC', 'NXPI', 'HBI', 'K', 'BR', 'PRGO', 'KMB',
       'KIM', 'ORCL', 'KR', 'LEG', 'LEN', 'LLY', 'LB', 'CHTR', 'LNC', 'L',
       'LOW', 'IEX', 'MMC', 'MAS', 'SPGI', 'MDT', 'VTRS', 'CVS', 'DD',
       'MU', 'MSI', 'CBOE', 'LH', 'NEM', 'NKE', 'NI', 'NSC', 'PFG', 'ES',
       'NOC', 'WFC', 'NUE', 'PVH', 'OXY', 'OMC', 'OKE', 'RJF', 'PH',
       'ROL', 'PPL', 'COP', 'PHM', 'PNW', 'PNC', 'PPG', 'PGR', 'PEG',
       'RHI', 'EIX', 'SLB', 'SCHW', 'SHW', 'WST', 'SJM', 'SNA', 'AME',
       'SO', 'TFC', 'LUV', 'WRB', 'SWK', 'PSA', 'ANET', 'SYY', 'CTVA',
       'TXN', 'TXT', 'TMO', 'TJX', 'GL', 'JCI', 'ULTA', 'UNP', 'KEYS',
       'UNH', 'UNM', 'MRO', 'BIO', 'VTR', 'VFC', 'VNO', 'VMC', 'WY',
       'WHR', 'WMB', 'WEC', 'ADBE', 'AES', 'AMGN', 'AAPL', 'ADSK', 'CTAS',
       'CMCSA', 'TAP', 'KLAC', 'MAR', 'MKC', 'PCAR', 'COST', 'FRC', 'SYK',
       'TSN', 'LW', 'AMAT', 'AAL', 'CAH', 'CERN', 'CINF', 'VIAC', 'DHI',
       'EA', 'EXPD', 'FAST', 'MTB', 'XEL', 'FISV', 'FITB', 'GILD', 'HAS',
       'HBAN', 'WELL', 'BIIB', 'NTRS', 'PKG', 'PAYX', 'PBCT', 'QCOM',
       'ROP', 'ROST', 'IDXX', 'SBUX', 'KEY', 'FOXA', 'FOX', 'STT', 'NCLH',
       'USB', 'AOS', 'NLOK', 'TROW', 'WM', 'STZ', 'XLNX', 'XRAY', 'ZION',
       'ALK', 'IVZ', 'LIN', 'INTU', 'MS', 'MCHP', 'CB', 'HOLX', 'CFG',
       'ORLY', 'ALL', 'EQR', 'BWA', 'OGN', 'HST', 'INCY', 'SPG', 'EMN',
       'TWTR', 'AVB', 'PRU', 'UPS', 'WBA', 'STE', 'MCK', 'LMT', 'ABC',
       'COF', 'WAT', 'DLTR', 'DRI', 'DPZ', 'NVR', 'NTAP', 'CTXS', 'DXC',
       'ODFL', 'DVA', 'HIG', 'IRM', 'EL', 'CDNS', 'TYL', 'UHS', 'SWKS',
       'NOV', 'DGX', 'ATVI', 'ROK', 'KHC', 'AMT', 'REGN', 'AMZN', 'JKHY',
       'RL', 'BXP', 'APH', 'HWM', 'PXD', 'VLO', 'SNPS', 'WU', 'ETSY',
       'CHRW', 'ACN', 'TDG', 'YUM', 'PLD', 'FE', 'VRSN', 'PWR', 'HSIC',
       'AEE', 'ANSS', 'NVDA', 'SEE', 'CTSH', 'SIVB', 'ISRG', 'TTWO',
       'RSG', 'EBAY', 'GS', 'SBAC', 'SRE', 'MCO', 'BKNG', 'FFIV', 'AKAM',
       'CRL', 'MKTX', 'DVN', 'GOOGL', 'TFX', 'NFLX', 'ALLE', 'A', 'ANTM',
       'TRMB', 'CME', 'JNPR', 'BLK', 'DTE', 'NDAQ', 'CE', 'PM', 'CRM',
       'IR', 'HII', 'MET', 'UA', 'TPR', 'CSX', 'EW', 'AMP', 'ZBRA', 'ZBH',
       'CBRE', 'MA', 'KMX', 'ICE', 'FIS', 'CMG', 'WYNN', 'LYV', 'AIZ',
       'NRG', 'RF', 'MNST', 'MOS', 'EXPE', 'EVRG', 'DISCA', 'CF', 'LDOS',
       'APA', 'GOOG', 'TEL', 'COO', 'DFS', 'V', 'MAA', 'XYL', 'MPC',
       'TSCO', 'AMD', 'RMD', 'MTD', 'CPRT', 'ALB', 'FTNT', 'ESS', 'O',
       'WRK', 'INFO', 'WAB', 'POOL', 'WDC', 'PEP', 'FANG', 'MXIM', 'NOW',
       'CHD', 'DRE', 'FRT', 'MGM', 'AEP', 'PTC', 'JBHT', 'LRCX', 'MHK',
       'PNR', 'VRTX', 'AMCR', 'FB', 'TMUS', 'URI', 'ABMD', 'HON', 'ARE',
       'DAL', 'STX', 'UAL', 'NWS', 'CNC', 'MLM', 'TER', 'PYPL', 'TSLA',
       'DISH', 'DOW', 'PENN', 'ALXN', 'RE', 'TDY', 'NWSA', 'EXC', 'GPN',
       'CCI', 'APTV', 'AAP', 'ALGN', 'ILMN', 'LKQ', 'NLSN', 'GRMN', 'ZTS',
       'EQIX', 'DLR', 'LVS', 'DISCK', 'HFC', 'FLIR', 'VAR', 'XRX', 'FLS',
       'CXO', 'SLG', 'TIF', 'FTI', '9990302D', 'VNT', 'NBL', 'MYL', 'AIV',
       'ETFC', 'HRB', 'KSS', 'COTY', 'M', 'HOG', 'HP', 'RTN', 'JWN',
       'AGN', 'CPRI', 'ADS', 'WCG', 'XEC', 'AMG', 'TRIP', 'MAC', 'STI',
       'CELG', 'VIAB', 'NKTR', 'APC', 'FL', 'JEF', 'TSS', 'LLL', 'RHT',
       'BHGE', 'UTX', 'CTL', 'HCP', 'JEC', 'BBT', 'TMK', 'SYMC', 'CBS',
       'ARNC', 'BHF', 'HRS', 'MAT', 'DWDP', 'FLR', 'TFCFA', 'PCG', 'SCG',
       'NFX', 'GT', 'TFCF', 'ESRX', 'AET', 'COL', 'CA', 'EQT', 'ANDV',
       'PX', 'SRCL', 'EVHC', 'XL', 'KDP', 'GGP', 'TWX', 'RRC', 'AYI',
       'CSRA', 'MON', 'WYND', 'NAVI', 'BCR', 'PDCO', 'CHK', 'SNI', 'SIG',
       'LVLT', 'BHI', '1697067D', 'MUR', 'BBBY', 'AN', 'SPLS', 'WFM',
       'RAI', 'RIG', 'MNK', 'TGNA', 'R', 'SWN', '1518855D', 'DNB', 'TDC',
       'MJN', 'FTR', 'HAR', 'LLTC', 'URBN', 'FSLR', 'PBI', 'STJ',
       '1539941D', 'ENDP', 'AA', 'LM', 'OI', 'DO', 'HOT', 'GAS', 'EMC',
       '1436513D', '1500785D', 'CPGX', 'ARG', 'CCEP', 'THC', '1566019D',
       'CVC', 'CAM', 'SNDK', 'TWC', 'GME', 'BXLT', 'POM', 'ESV',
       '9876566D', 'PCL', 'PCP', 'BRCM', 'CNX', 'FOSL', 'GMCR', 'CSC',
       'JOY', 'SIAL', '1541931D', 'HCBK', 'GNW', 'CMCSK', '9876549D',
       'FDO', 'TEG', 'NE', '1684442D', 'KRFT', 'ATI', 'QEP', 'MWV',
       '1448062D', 'HSP', 'LO', 'WINMQ', '1288453D', '1284849D', 'AVP',
       'NBR', 'DNR', 'SWY', 'COV', 'CFN', 'PETM', 'BMS', 'JBL', 'BTUUQ',
       'RDC', 'X', 'GHC', 'FRX', 'BEAM', 'CLF', '9876544D', 'SLM',
       '1431816D', 'WPX', '1255459D', 'JCP', '1683997D', 'MOLX', 'VIAV',
       'ANF', 'NYX', '0848680D', 'BMC', 'APOL', 'HNZ', 'CVH', 'FHN', 'DF',
       'BIG', 'FII', 'CBE', 'RRD', '1086832D', 'ATGE', 'LXK', 'TIE',
       'ANRZQ', 'GR', '0961514D', 'SHLDQ', 'EP', 'HSH', 'SVU', '1280712D',
       'MHS', '0867887D', 'CEG', '1519128D', 'TLAB', 'AKS', 'SUNEQ',
       'MWW', '0111145D', 'JNS', 'ITT', 'CEPH', '0203524D', 'MI', 'RSHCQ',
       '8394653Q', 'MEE', 'NOVL', 'GENZ', '0772031D', 'MFE', 'AYE',
       'QLGC', 'MDP', 'EKDKQ', 'ODP', 'NYT', 'KG', 'PTV', '0202445Q',
       'SII', 'STR', 'XTO', '1524867D', 'BDK', 'RX', 'PBG', 'BNI',
       '8277831Q', 'JAVA', 'SGP', 'WYE', 'KBH', 'MBI', 'DYNIQ', 'CIEN',
       'CVG', '0226226D', 'CITGQ', '1654539D', 'MTW', 'MTLQQ', 'ROH',
       'SITC', 'SOV', '3517233Q', '1255173D', 'MER', 'NCC', 'JNY', 'ACAS',
       'WFT', 'BRL', 'AW', '3286728Q', '3393199Q', 'WWY', 'KATE', 'ASH',
       'HPC', 'UIS', 'TEX', 'MTG', 'DDS', '3022239Q', '1649858D',
       '3423152Q', '2968900Q', 'CFC', 'WAMUQ', 'LEHMQ', 'FMCC', 'FNMA',
       'IAC', 'SSP', '2942331Q', 'OMX', 'BC', 'ABKFQ', '1520415D',
       'CCTYQ', 'HET', 'SNV', 'TRB', 'DJ', '3692470Q', 'TEK', 'HCR',
       'BOL', '0574018D', '2641504Q', 'TIN', '3414924Q', '0910150D',
       'TXU', 'NCR', '1317355D', '8206908Q', 'KSE', '0964591D',
       '3403545Q', 'MEL', 'ADCT', 'PMCS', 'SANM', 'MEDI', '3362726Q',
       '1528159D', '4621824Q', '1293405D', 'CMX', '1704453D', 'HMA',
       'PGL', '2307532Q', 'EOP', '2987536Q', 'BLS', 'CMVT', 'FSL/B',
       'NFB', 'LU', '3605818Q', 'FSH', '3133754Q', 'GDW', 'ANDW', 'NAV',
       '1281683D', 'LPX', '0544749D', 'CAR', 'GTW', 'CTB', 'KRI',
       '2999130Q', '1312089D', 'GDT', '1683351D', '929530Q', 'CIN',
       '3080867Q', 'AMCC', '1288652D', 'DCNAQ', '3026360Q', 'RBK', 'SEBL',
       'MERQ', 'KRB', 'VSTNQ', '653707Q', 'GP', 'CPNLQ', 'DPHIQ',
       '1028411Q', 'PVN', '987200Q', 'DALRQ', 'NXTL', '764144Q', 'UCL',
       'TOY', '723588Q', '3153670Q', '605555Q', 'PWER', '3029830Q',
       'WNDXQ', '2676187Q', 'AWE', 'CR', 'DLX', 'WOR', '502466Q',
       '605018Q', '3621240Q', 'UPC', '355488Q', 'TNB', 'JHF', '945852Q',
       'TAP/B', 'FBF', '0948669D', '519239Q', 'TUP', 'BGEN', 'QTRN',
       'MIRKQ', 'MDR', '748957Q', '2727195Q', 'RATL', 'EHC', 'AAMRQ',
       '297504Q', 'GOLD', 'NRTLQ', 'UN', 'COC', 'PALM', 'CNCEQ',
       '8214761Q', 'INCLF', 'PDG', 'RDPL', 'IMNX', 'VTSS', '1040983D',
       'SAPE', 'UAWGQ', 'WCOEQ', '680884Q', '228510Q', 'NMK', '544791Q',
       '1051665D', 'KMRTQ', 'HM', 'RAL', '329556Q', 'ENRNQ', 'GPUI',
       '677004Q', 'GBLXQ', '41018Q', 'BVSN', 'TKR', 'PCH', 'TOS',
       '950967Q', 'ETS', 'OAT', 'LDG', 'SXCL', 'BGG', 'ARB', '739306Q',
       'AZA', '89236Q', 'RTN/B', 'OK', '3277Q', '3075558Q', '3346Q',
       '1255177D', 'CGP', '253647Q'], dtype=object)

### Export CSV

In [13]:
### Look at the df before exporting
df

,Date,Ticker,Name,Sector,Price,Local_Returns_12m,Local_Returns_1m,Trail_DivYld,PB,Trail_EV_EBITDA,Trail_PE,Trail_EPS,Trail3yrAvg_EPSgro,Trail3yrAvg_DPSgro,Volatility,Debt_to_MktCap,NetDebt_EBITDA
0,2021-06-30,LYB,LYONDELLBASELL-A,Materials,102.8700,0.639834,-0.077692,4.1606,3.9080,13.3578,13.4336,7.6577,16.9882,4.0447,40.193,0.4833,3.9745
1,2021-06-30,AXP,AMERICAN EXPRESS,Financials,165.2300,0.762142,0.031849,1.0410,5.4268,11.4500,27.1314,8.6000,165.5851,7.8788,34.862,0.3285,0.3249
2,2021-06-30,VZ,VERIZON COMMUNIC,Communication Services,56.0300,0.061385,-0.008143,4.4574,3.1481,8.6097,10.4378,5.3680,10.8359,2.0861,15.239,0.7723,3.6833
3,2021-06-30,AVGO,BROADCOM INC,Information Technology,476.8400,0.561110,0.017371,2.9465,9.6650,17.2061,40.4239,11.7960,23.7943,30.8588,30.250,0.2067,2.3997
4,2021-06-30,BA,BOEING CO/THE,Industrials,239.5600,0.306928,-0.030200,0.0000,NaN,NaN,NaN,-8.1120,-51.6859,0.0000,46.282,0.4538,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124725,2000-12-31,MDR,MCDERMOTT INTL,Energy,NaN,0.198454,0.194444,2.7033,0.4328,12.0836,20.5509,NaN,NaN,-9.1440,68.622,0.6455,3.8149
124726,2000-12-31,EHC,ENCOMPASS HEALTH,Health Care,81.5625,2.034884,0.170404,0.0000,NaN,NaN,NaN,NaN,NaN,0.0000,68.515,NaN,NaN
124727,2000-12-31,AAMRQ,AMR CORP,Industrials,39.1875,0.307889,0.171963,0.0000,0.8304,NaN,8.4821,4.6200,-46.7452,0.0000,51.599,1.0618,1.5629
124728,2000-12-31,CMCSK,COMCAST CORP-SPL,Communication Services,27.8333,-0.174289,0.086179,0.0000,2.7026,19.0587,2065.6250,-0.0067,NaN,0.0000,59.400,0.2869,2.8742
124729,2000-12-31,VTSS,MICROCHIP COMMUN,Information Technology,1106.2500,0.054827,0.282609,0.0000,8.6338,36.6065,80.1630,13.8000,66.4983,0.0000,114.207,0.0721,-0.1106

In [14]:
### Export the gathered data to a csv file

#df.to_csv("SP500_Index_Data_partial_clean.csv", index=False)